In [17]:
import glob
import pandas as pd
from pathlib import Path
from typing import Callable

files = glob.glob("/g/data/ct11/access-nri/replicas/esmvaltool/**/*.nc",recursive=True)
print(f"No. of obs6 files: {pd.Series(files).str.lower().str.contains('obs6').sum()}")
srs = pd.Series(files)
srs.name='path'

for f in files[:10]:
    print(f)

No. of obs6 files: 2886
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Emon_tdps_201701-201712.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_rsds_201101-201112.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_hur_199401-199412.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_rsutcs_199401-199412.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_vas_200801-200812.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_rsut_198101-198112.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_tauu_199201-199212.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_ua_200801-200812.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_Amon_rsutcs_198901-198912.nc
/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier3/ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_vas_198801-198812.nc

In [84]:
def get_tier(file_path : str) -> str:
    """ Split the parts, find the one that is 
    either Tier1, Tier2, or Tier3.
    """
    path_parts = Path(file_path).parts
    for part in path_parts:
        if part in ['Tier1', 'Tier2', 'Tier3']:
            return part
    return None

def filter_for_str(srs: pd.Series, filter_str: str) -> pd.Series:
    """ Apply filtering function to each file path and expand results into separate columns """
    if not isinstance(srs, pd.Series):
        raise TypeError(f'Wrong dtype, probably the wrong input source. Expected {type(srs)}=pd.Series, got {type(srs)=}')
    
    return srs[
        srs.str.lower().str.contains(filter_str)
    ].reset_index(drop=True)

def split(filtered_srs: pd.Series, split_func: Callable) -> pd.DataFrame:
    """
    Take our filtered series & split out the various identifiers in the file stems using
    the `split_func` we pass in.
    """
    COLNAMES = ['project_id', 'source_id', 'experiment_id', 'version',  'table_id', 'variable_id', 'time_range', 'tier']
    df = pd.DataFrame(filtered_srs)
    df[['project_id', 'source_id', 'experiment_id', 'version', 'table_id', 'variable_id', 'time_range', 'tier']] = df['path'].apply(lambda x: pd.Series(split_func(x)))
    return df

In [85]:
from pathlib import Path
from typing import Callable

# Function to split the filename into components based on '_'
def split_filename_obs6(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [project_id, source_id, experiment_id, version, table_id, variable_id, time_range, *_]:
            return {
                'project_id': project_id,
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': version,
                'table_id': table_id,
                'variable_id': variable_id,
                'time_range': time_range,
                'tier' : get_tier(file_path),
            }
        case [project_id, source_id, experiment_id, version, table_id, variable_id]:
            return {
                'project_id': project_id,
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': version,
                'table_id': table_id,
                'variable_id': variable_id,
                'time_range': None,
                'tier' : get_tier(file_path),
            }  
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )
            


obs6_srs = filter_for_str(srs,'obs6')
obs6_df = split(obs6_srs, split_filename_obs6)

In [86]:
df_all = pd.DataFrame(pd.Series(files))
df_all.columns = ['path']
df_remaining = df_all[~pd.Series(files).str.lower().str.contains('obs6')].copy().reset_index(drop=True)

obs4mips_srs = filter_for_str(srs,'obs4mips')
obs4mips_df = pd.DataFrame(obs4mips_srs)


def split_filename_obs4mips(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    
    if "-" in components[-1]:
        time_range = components[-1]
    else:
        time_range = "-".join([components[-2], components[-1]])
    return {
        'project_id': "obs4MIPs",
        'source_id': components[2],
        'version': components[4],
        'variable_id': components[0],
        'time_range': time_range,
        'tier' : get_tier(file_path),
        } 
    
# Apply function to each file path and expand results into separate columns

obs4mips_df[['project_id', 'source_id', 'version', 'variable_id', 'time_range','tier']] = obs4mips_df['path'].apply(lambda x: pd.Series(split_filename_obs4mips(x)))
obs4mips_df

,path,project_id,source_id,version,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CALIOP,CALIPSO-GOCCP-v2.1,cllcalipso,20071201-20071231,Tier1
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CALIOP,CALIPSO-GOCCP-v2.1,clhcalipso,20100501-20100531,Tier1
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CALIOP,CALIPSO-GOCCP-v2.1,clmcalipso,20080801-20080831,Tier1
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CALIOP,CALIPSO-GOCCP-v2.1,clccalipso,20080701-20080731,Tier1
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CALIOP,CALIPSO-GOCCP-v2.1,cllcalipso,20090501-20090531,Tier1
...,...,...,...,...,...,...,...
1741,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,ISCCP,V1.0,albisccp,200402-200402,Tier1
1742,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,ISCCP,V1.0,albisccp,199504-199504,Tier1
1743,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,ISCCP,V1.0,albisccp,200001-200001,Tier1
1744,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,ISCCP,V1.0,cltisccp,198812-198812,Tier1
1745,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,ISCCP,V1.0,clisccp,199908-199908,Tier1

In [87]:
def split_filename_CFSR(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `zg_Amon_reanalysis_CFSR_201301-201312` which get mapped as
    f{variable_id}_{table_id}_{experiment_id}_{source_id}_{time_range}
    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [variable_id, table_id, experiment_id, source_id, time_range]:
            return {
                'project_id': "obs4MIPs",
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': None,
                'table_id': table_id,
                'variable_id': variable_id,
                'time_range': time_range,
                'tier' : get_tier(file_path),
            }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )


cfsr_srs = filter_for_str(srs,'cfsr')
cfsr_df = split(cfsr_srs, split_filename_CFSR)

cfsr_df

,path,project_id,source_id,experiment_id,version,table_id,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,zg,201301-201312,Tier1
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,va,200601-200612,Tier1
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,zg,198101-198112,Tier1
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,zg,200701-200712,Tier1
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,zg,198501-198512,Tier1
...,...,...,...,...,...,...,...,...,...
165,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,ua,201101-201112,Tier1
166,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,zg,200201-200212,Tier1
167,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,ua,199601-199612,Tier1
168,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,ua,199901-199912,Tier1
169,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CFSR,reanalysis,None,Amon,zg,200501-200512,Tier1

In [88]:
def split_filename_CERES_EBAF(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `rlds_CERES-EBAF_L3B_Ed2-7_200003-201209` which get mapped as
    f{variable_id}_{source_id}_{experiment_id}_{version_}_{time_range}
    or 
    `OBS_CERES-EBAF_sat_Ed4.0_Amon_rsut_200003-201812` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{version}_{table_id}_{variable_id}_{time_range}"

    
    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [variable_id, source_id, experiment_id, version, time_range]:
            return {
                'project_id': "obs4MIPs",
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': version,
                'table_id': None,
                'variable_id': variable_id,
                'time_range': time_range,
                'tier' : get_tier(file_path),
            }
        case [project_id, source_id, experiment_id, version, table_id, variable_id, time_range]:
            return {
                'project_id': project_id,
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': version,
                'table_id': table_id,
                'variable_id': variable_id,
                'time_range': time_range,
                'tier' : get_tier(file_path),
            }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )


ceres_ebaf_srs = filter_for_str(srs,'ceres-ebaf')
ceres_ebaf_df = split(ceres_ebaf_srs, split_filename_CERES_EBAF)

ceres_ebaf_df

,path,project_id,source_id,experiment_id,version,table_id,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.0,Amon,rsut,200003-201812,Tier2
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.0,Amon,rlutcs,200003-201812,Tier2
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.1,Amon,rlut,200003-202203,Tier2
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.1,Amon,rsut,200003-202203,Tier2
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.1,Amon,rsutcs,200003-202203,Tier2
5,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.1,Amon,rlutcs,200003-202203,Tier2
6,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.0,Amon,rsutcs,200003-201812,Tier2
7,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,CERES-EBAF,sat,Ed4.0,Amon,rlut,200003-201812,Tier2
8,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsdscs,200003-201311,Tier1
9,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rlus,200003-201311,Tier1
10,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rldscs,200003-201311,Tier1
11,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsus,200003-201311,Tier1
12,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsds,200003-201311,Tier1
13,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rlds,200003-201311,Tier1
14,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsuscs,200003-201311,Tier1
15,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsdscs,200003-201209,Tier1
16,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsdt,200003-201605,Tier1
17,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsus,200003-201602,Tier1
18,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsdt,200003-201302,Tier1
19,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rlutcs,200003-201302,Tier1
20,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsuscs,200003-201602,Tier1
21,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsds,200003-201602,Tier1
22,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rlut,200003-201605,Tier1
23,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsut,200003-201302,Tier1
24,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rlds,200003-201209,Tier1
25,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsuscs,200003-201209,Tier1
26,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsus,200003-201209,Tier1
27,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rlutcs,200003-201605,Tier1
28,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsutcs,200003-201605,Tier1
29,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rlus,200003-201209,Tier1
30,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rldscs,200003-201602,Tier1
31,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rlut,200003-201302,Tier1
32,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsdscs,200003-201602,Tier1
33,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rldscs,200003-201209,Tier1
34,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsds,200003-201209,Tier1
35,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rlus,200003-201602,Tier1
36,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-7,None,rsutcs,200003-201302,Tier1
37,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rlds,200003-201602,Tier1
38,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,obs4MIPs,CERES-EBAF,L3B,Ed2-8,None,rsut,200003-201605,Tier1

In [89]:
# 
def split_filename_JRA55(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `rsut_Amon_reanalysis_JRA-55_195801-201912` which get mapped as
    f{variable_id}_{table_id}_{experiment_id}_{source_id}_{time_range}
    or 
    `OBS6_JRA-55_reanaly_1_Amon_tas_195801-202212` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{version}_{table_id}_{variable_id}_{time_range}"

    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [variable_id, table_id, experiment_id, source_id, time_range]:
            return {
                'project_id': "obs4MIPs",
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': None,
                'table_id': table_id,
                'variable_id': variable_id,
                'time_range': time_range,
                'tier' : get_tier(file_path),
            }
        case [_, source_id, experiment_id, version, table_id, variable_id, time_range]:
            return {
                'project_id': "OBS6",
                'source_id': source_id,
                'experiment_id': experiment_id,
                'version': version,
                'table_id': table_id,
                'variable_id': variable_id,
                'time_range': time_range,
                'tier' : get_tier(file_path),
            }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )

jra55_srs = filter_for_str(srs,'jra-55')
jra55_df = split(jra55_srs, split_filename_JRA55)


jra55_flist = jra55_df['path'].tolist()
obs6_flist = obs6_df['path'].tolist()

### For whatever reason about half of these overlap? IDK, We drop the duplicates later on 
print(len(set(jra55_flist).intersection(set(obs6_flist))))
print(len(jra55_df))

16
29

In [98]:
#  '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ESACCI-SST/OBS_ESACCI-SST_sat_2.2_Amon_ts_201901-201912.nc',
# '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ESACCI-SST/OBS_ESACCI-SST_sat_L4-GHRSST-SSTdepth-OSTIA-GLOB_Amon_tsStderr_199201-199201.nc'

def split_filename_ESACCI(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `OBS_ESACCI-SST_sat_2.2_Amon_ts_201901-201912` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{version}_{table_id}_{variable_id}_{time_range}"
    or 
    `OBS_ESACCI-SST_sat_L4-GHRSST-SSTdepth-OSTIA-GLOB_Amon_tsStderr_199201-199201` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{grid_label}_{table_id}_{variable_id}_{time_range}"
    or
    `xco2_ghgcci_l3_v100_200301_201412.nc`, which get mapped as
    f"{variable_id`_{source_id}_{grid_label}_{version}_{t1}_{t2}" => f"{variable_id`_{}_{}_{version}_{time_range}"
    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [project_id, source_id, experiment_id, version, table_id, variable_id, time_range]:
            return {
                    'project_id': project_id,
                    'source_id': source_id,
                    'experiment_id': experiment_id,
                    'version': version,
                    'table_id': table_id,
                    'variable_id': variable_id,
                    'time_range': time_range,
                    'tier' : get_tier(file_path),
                }
        case [variable_id, source_id, version, _, t_start, t_end]:
            return {
                'project_id': "Obs4MIPs",
                'source_id': source_id,
                'experiment_id': None,
                'version': version,
                'table_id': None,
                'variable_id': variable_id,
                'time_range': f"{t_start}-{t_end}",
                'tier' : get_tier(file_path),
            }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )

esacci_srs = filter_for_str(srs,'esacci')
esacci_df = split(esacci_srs, split_filename_ESACCI)

esacci_df

,path,project_id,source_id,experiment_id,version,table_id,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-SOILMOISTURE,sat,L3S-SSMV-COMBINED-v4.2,Lmon,sm,197901-201612,Tier2
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-SOILMOISTURE,sat,L3S-SSMV-COMBINED-v4.2,Lmon,smStderr,197901-201612,Tier2
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-SOILMOISTURE,sat,L3S-SSMV-COMBINED-v4.2,Lmon,dosStderr,197901-201612,Tier2
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-SOILMOISTURE,sat,L3S-SSMV-COMBINED-v4.2,Lmon,dos,197901-201612,Tier2
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS6,ESACCI-OC,sat,fv5.0,Omon,chl,199709-202012,Tier2
...,...,...,...,...,...,...,...,...,...
595,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-OZONE,sat,L3,Amon,tozStderr,199701-201012,Tier2
596,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-OZONE,sat,L3,Amon,toz,199701-201012,Tier2
597,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESACCI-OZONE,sat,L3,Amon,tro3prof,200701-200812,Tier2
598,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,Obs4MIPs,ghgcci,None,l3,None,xco2,200301-201412,Tier1
599,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,Obs4MIPs,ghgcci,None,l3,None,xch4,200301-201412,Tier1

In [97]:
# '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ESRL/OBS_ESRL_ground_PAL_Amon_co2s_200112-201912.nc',

def split_filename_ESRL(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `OBS_ESRL_ground_PAL_Amon_co2s_200112-201912.nc` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{_}_{table_id}_{variable_id}_{time_range}"
 
    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [project_id, source_id, experiment_id, _, table_id, variable_id, time_range]:
            return {
                    'project_id': project_id,
                    'source_id': source_id,
                    'experiment_id': experiment_id,
                    'version': None,
                    'table_id': table_id,
                    'variable_id': variable_id,
                    'time_range': time_range,
                    'tier' : get_tier(file_path),
                }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )

esrl_srs = filter_for_str(srs,'esrl')
esrl_df = split(esrl_srs, split_filename_ESRL)

esrl_df

,path,project_id,source_id,experiment_id,version,table_id,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,197903-199008,Tier2
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,201003-201912,Tier2
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,199710-200908,Tier2
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,198001-202008,Tier2
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,199901-201105,Tier2
...,...,...,...,...,...,...,...,...,...
89,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,200204-201705,Tier2
90,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,197908-201912,Tier2
91,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,198612-201707,Tier2
92,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,199701-201912,Tier2
93,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,ESRL,ground,None,Amon,co2s,198404-201912,Tier2

In [102]:
#  '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/NCEP/OBS_NCEP_reanaly_1_Amon_zg_201001-201012.nc',

def split_filename_NCEP(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `OBS_NCEP_reanaly_1_Amon_zg_201001-201012.nc` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{version}_{table_id}_{variable_id}_{time_range}"
 
    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [project_id, source_id, experiment_id, version, table_id, variable_id, time_range]:
            return {
                    'project_id': project_id,
                    'source_id': source_id,
                    'experiment_id': experiment_id,
                    'version': version,
                    'table_id': table_id,
                    'variable_id': variable_id,
                    'time_range': time_range,
                    'tier' : get_tier(file_path),
                }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )

ncep_srs = filter_for_str(srs,'ncep')
ncep_df = split(ncep_srs, split_filename_NCEP)

ncep_df

,path,project_id,source_id,experiment_id,version,table_id,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS6,NCEP-DOE-R2,reanaly,2,Amon,wap,197901-202409,Tier2
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS6,NCEP-DOE-R2,reanaly,2,Amon,hur,197901-202409,Tier2
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS6,NCEP-DOE-R2,reanaly,2,Amon,tauu,197901-202409,Tier2
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS6,NCEP-DOE-R2,reanaly,2,Amon,clt,197901-202409,Tier2
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS6,NCEP-DOE-R2,reanaly,2,Amon,prw,197901-202409,Tier2
...,...,...,...,...,...,...,...,...,...
1248,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,NCEP,reanaly,1,day,rlut,199501-199512,Tier2
1249,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,NCEP,reanaly,1,day,pr,198601-198612,Tier2
1250,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,NCEP,reanaly,1,Amon,zg,196501-196512,Tier2
1251,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,NCEP,reanaly,1,day,pr,195501-195512,Tier2
1252,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,NCEP,reanaly,1,day,pr,197801-197812,Tier2

In [106]:
#  '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/WFDE5/OBS_WFDE5_ground_v1.1-CRU_day_tas_201301-201312.nc',

def split_filename_WFDE(file_path : str) -> dict[str, str | None]:
    """
    Take a filename & split it's stem on occurences of `_`. This
    returns a dictionary which we can then use to create a new 
    dataframe with all the various fields.

    These are of the form:
    `OBS_WFDE5_ground_v1.1-CRU_day_tas_201301-201312.nc` which get mapped as
    f"{project_id}_{source_id}_{experiment_id}_{version}_{table_id}_{variable_id}_{time_range}"
 
    
    """
    # Remove the file extension and split the rest based on '_'
    components = Path(file_path).stem.split('_')
    # Return components in a dictionary format for DataFrame usage
    match components:
        case [project_id, source_id, experiment_id, version, table_id, variable_id, time_range]:
            return {
                    'project_id': project_id,
                    'source_id': source_id,
                    'experiment_id': experiment_id,
                    'version': version,
                    'table_id': table_id,
                    'variable_id': variable_id,
                    'time_range': time_range,
                    'tier' : get_tier(file_path),
                }
        case _:
            raise RuntimeError(
                f"Unable to match all rows: failed on path {file_path}"
            )

wfde_srs = filter_for_str(srs,'wfde')
wfde_df = split(wfde_srs, split_filename_WFDE)

wfde_df

,path,project_id,source_id,experiment_id,version,table_id,variable_id,time_range,tier
0,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU+GPCC,day,pr,199401-199412,Tier2
1,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,tas,199401-199412,Tier2
2,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,tas,200401-200412,Tier2
3,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU+GPCC,day,pr,199501-199512,Tier2
4,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,pr,198001-198012,Tier2
...,...,...,...,...,...,...,...,...,...
227,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,tas,200501-200512,Tier2
228,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,day,tas,198601-198612,Tier2
229,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,pr,200401-200412,Tier2
230,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,pr,201301-201312,Tier2
231,/g/data/ct11/access-nri/replicas/esmvaltool/ob...,OBS,WFDE5,ground,v1.1-CRU,Amon,pr,198601-198612,Tier2

In [107]:
merged_df_1 = pd.concat([obs6_df, obs4mips_df, cfsr_df, ceres_ebaf_df, jra55_df, esacci_df, esrl_df, ncep_df, wfde_df]).reset_index(drop=True).drop_duplicates()

In [108]:
nfiles_todo = len(srs) - len(merged_df_1)
print(f"Remaining files: {nfiles_todo}")

Remaining files: 550

In [109]:
files_to_do = set(srs) - set(merged_df_1.path)
sorted(files_to_do)

['/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-0/hur_AIRS-2-0_L3_v2_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-1/hur_AIRS-2-1_BE_gn_200209-201609.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-1/hur_mon_AIRS-2-1_BE_gn_200209-201609.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-1/hus_AIRS-2-1_BE_gn_200209-201609.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-1/hus_mon_AIRS-2-1_BE_gn_200209-201609.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-1/ta_AIRS-2-1_BE_gn_200209-201609.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS-2-1/ta_mon_AIRS-2-1_BE_gn_200209-201609.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS/husNobs_AIRS_L3_RetStd-v5_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS/husStderr_AIRS_L3_RetStd-v5_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS/hus_AIRS_L3_RetStd-v5_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS/taNobs_AIRS_L3_RetStd-v5_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS/taStderr_AIRS_L3_RetStd-v5_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/AIRS/ta_AIRS_L3_RetStd-v5_200209-201105.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/ATSR/tosAnom_ATSR_L3_ARC-v1.1.1_199701-201112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/ATSR/tos_ATSR_L3_ARC-v1.1.1_199701-201112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/prStderr_GPCP-SG_L3_v2.2_197901-197912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/prStderr_GPCP-SG_L3_v2.2_198001-198912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/prStderr_GPCP-SG_L3_v2.2_199001-199912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/prStderr_GPCP-SG_L3_v2.2_200001-200912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/prStderr_GPCP-SG_L3_v2.2_201001-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_197901-197912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_198001-198912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_199001-199912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_200001-200912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_201001-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.3_197901-201710.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-V2.2/pr_GPCP-SG_L3_v2.2_197901-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-V2.3/pr_GPCP-SG_L3_v2.3_197901-201710.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-V2.3/v20180519/pr_GPCP-SG_L3_v2.3_197901-201710.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS-1-0/clt_mon_MODIS-1-0_BE_gn_200003-201109.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/cltNobs_MODIS_L3_C5_200003-201109.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/cltStddev_MODIS_L3_C5_200003-201109.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/clt_MODIS_L3_C5_200003-201109.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/cltcalipso_MODIS_L3_C5_200003-201109.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/cltisccp_MODIS_L3_C5_200003-201109.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/fpar_MODIS-Level_3_v5_200002-200912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/lai_MODIS-level_3_v5_200002-200912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/od550aerNobs_MODIS_L3_C5_200003-201212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/od550aerStdv_MODIS_L3_C5_200003-201212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/MODIS/od550aer_MODIS_L3_C5_200003-201212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/SSMI-MERIS/prwErr_SSMI-MERIS_L3_v1-00_200301-200812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/SSMI-MERIS/prwFlag_SSMI-MERIS_L3_v1-00_200301-200812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/SSMI-MERIS/prwStddev_SSMI-MERIS_L3_v1-00_200301-200812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/SSMI-MERIS/prw_SSMI-MERIS_L3_v1-00_200301-200812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/SSMI/prw_SSMI_L3_RSSv07r00_198801_201512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/TRMM-L3/prStderr_TRMM-L3_v7-7A_199801-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/TRMM-L3/prStderr_TRMM-L3_v7_7A_199801-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/TRMM-L3/pr_TRMM-L3_v7-7A_199801-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/TRMM-L3/pr_TRMM-L3_v7_7A_199801-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/TRMM/v20160613/prStderr_TRMM-L3_v7-7A_199801-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/TRMM/v20160613/pr_TRMM-L3_v7-7A_199801-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/ghgcci/xch4_ghgcci_l3_v100_200301_201412.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/ghgcci/xco2_ghgcci_l3_v100_200301_201412.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/BerkeleyEarth/OBS_BerkeleyEarth_reanaly_2020_Amon_tas_185001-201912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/BerkeleyEarth/OBS_BerkeleyEarth_reanaly_2020_Amon_tasa_185001-201912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/BerkeleyEarth/OBS_BerkeleyEarth_reanaly_2020_fx_sftlf.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CALIPSO-GOCCP/OBS_CALIPSO-GOCCP_sat_3.1.2_cfMon_clcalipso_200701-201512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CRU/OBS_CRU_reanaly_TS4.02_Amon_pr_190101-201712.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CRU/OBS_CRU_reanaly_TS4.02_Amon_tas_190101-201712.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CRU/OBS_CRU_reanaly_TS4.04-stn1_Amon_pr_190101-201912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CRU/OBS_CRU_reanaly_TS4.04-stn1_Amon_tas_190101-201912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CRU/OBS_CRU_reanaly_TS4.04_Amon_pr_190101-201912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CRU/OBS_CRU_reanaly_TS4.04_Amon_tas_190101-201912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_ghcn_short_krig_v2_Amon_tasa_197901-201908.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_ghcn_short_uah_v2_Amon_tasa_197901-201707.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_had4_krig_v1_Amon_tasa_197901-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_had4_krig_v2_Amon_tasa_185001-201911.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_had4_short_krig_v2_Amon_tasa_197901-201911.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_had4_short_uah_v2_Amon_tasa_197901-201707.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_had4_uah_v1_Amon_tasa_197901-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/CowtanWay/OBS_CowtanWay_reanaly_had4sst4_krig_v2_Amon_tasa_185001-201812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/Duveiller2018/OBS_Duveiller2018_clim_v2018_Amon_albDiffiTr13_201001-201012.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_Amon_pr_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_Amon_psl_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_Amon_tas_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_Amon_tasmax_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_Amon_tasmin_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_day_pr_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_day_psl_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_day_tas_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_day_tasmax_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.1_day_tasmin_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_Amon_pr_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_Amon_psl_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_Amon_tas_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_Amon_tasmax_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_Amon_tasmin_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_day_pr_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_day_psl_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_day_tas_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_day_tasmax_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/E-OBS/OBS_E-OBS_ground_v20.0e-0.25_day_tasmin_195001-201907.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/Eppley-VGPM-MODIS/OBS_Eppley-VGPM-MODIS_sat_R2018_Omon_intpp_200207-201903.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GCP2018/OBS_GCP2018_reanaly_1.0_Lmon_nbp_195906-201706.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GCP2018/OBS_GCP2018_reanaly_1.0_Omon_fgco2_195906-201706.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GCP2020/OBS_GCP2020_reanaly_1.0-residual_Lmon_nbp_195906-201906.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GCP2020/OBS_GCP2020_reanaly_1.0_Lmon_nbp_195906-201906.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GCP2020/OBS_GCP2020_reanaly_1.0_Omon_fgco2_195906-201906.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GHCN-CAMS/OBS_GHCN-CAMS_ground_1_Amon_tas_194801-202002.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GHCN/OBS_GHCN_ground_1_Amon_pr_190001-201412.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GISTEMP/OBS_GISTEMP_ground_v4_Amon_tasa_188001-202001.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_025-numgauge1_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_025_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_05-numgauge1_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_05_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_10-numgauge1_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_10_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_25-numgauge1_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCC/OBS_GPCC_reanaly_v2018_25_Amon_pr_189101-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/GPCP-SG/OBS_GPCP-SG_atmos_2.3_Amon_pr_197901-202304.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HALOE/OBS_HALOE_sat_1_Amon_hus_199101-200212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HALOE/OBS_HALOE_sat_1_Amon_tro3_199101-200212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT3/OBS_HadCRUT3_ground_1_Amon_tasa_185001-201312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT4/OBS_HadCRUT4_ground_1_Amon_tasConf5_185001-201812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT4/OBS_HadCRUT4_ground_1_Amon_tasConf95_185001-201812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT4/OBS_HadCRUT4_ground_1_Amon_tas_185001-201812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT4/OBS_HadCRUT4_ground_1_Amon_tasa_185001-201812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT5/OBS_HadCRUT5_ground_5.0.1.0-analysis_Amon_tas_185001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT5/OBS_HadCRUT5_ground_5.0.1.0-analysis_Amon_tasa_185001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT5/OBS_HadCRUT5_ground_5.0.1.0-noninfilled_Amon_tas_185001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT5/OBS_HadCRUT5_ground_5.0.1.0-noninfilled_Amon_tasa_185001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT5/OBS_HadCRUT5_ground_analysis_Amon_tas_185001-202012.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadCRUT5/OBS_HadCRUT5_ground_noninfilled_Amon_tas_185001-202012.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadISST/OBS_HadISST_reanaly_1_OImon_sic_187001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/HadISST/OBS_HadISST_reanaly_1_Omon_tos_187001-202112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_alb_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_prw_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_ps_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rlds_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rlus_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rlut_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rlutcs_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rsds_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rsdt_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rsus_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rsut_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_rsutcs_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_tas_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/ISCCP-FH/OBS_ISCCP-FH_sat_v0_Amon_ts_198401-201612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/Kadow2020/OBS_Kadow2020_ground_5.0.1.0_Amon_tasa_185001-202012.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/Landschuetzer2016/OBS_Landschuetzer2016_clim_v2016_Omon_dpco2_198201-201512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/Landschuetzer2016/OBS_Landschuetzer2016_clim_v2016_Omon_fgco2_198201-201512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/Landschuetzer2016/OBS_Landschuetzer2016_clim_v2016_Omon_spco2_198201-201512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/NOAAGlobalTemp/OBS_NOAAGlobalTemp_ground_v5.0.0_Amon_tasa_188001-202205.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_197901-197912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198001-198012.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198101-198112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198201-198212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198301-198312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198401-198412.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198501-198512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198601-198612.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198701-198712.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198801-198812.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_198901-198912.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199001-199012.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199101-199112.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199201-199212.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199301-199312.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199401-199412.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199501-199512.nc',
 '/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier2/OSI-450-nh/OBS_OSI-450-nh_reanaly_v2_OImon_sic_199601-199612.nc',